"""Módulo de declaração dos parsers e argumentos da CLI do AMB_V2."""
import argparse
from cli_modules.cli_handlers import (
    cmd_setup, cmd_prompt, cmd_check, cmd_monitor, cmd_advisor, cmd_gui,
    cmd_config, cmd_agent, cmd_jules, cmd_stitch, cmd_validate,
    cmd_pipeline, cmd_schema, cmd_context, cmd_antigravity, cmd_git
)

def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="amb",
        description="CLI Unificada do AMB_V2 — Automação, Agentes e Integrações para Monorepos e Projetos."
    )
    subs = parser.add_subparsers(dest="command", help="Comandos disponíveis")

    def _c(name, h, fn, als=None):
        p = subs.add_parser(name, aliases=als or [], help=h)
        p.set_defaults(func=fn)
        return p

    def _sc(ps, name, h, als=None):
        return ps.add_parser(name, aliases=als or [], help=h)

    def _j(p):
        p.add_argument("--json", action="store_true", help="Exibe a saída em formato JSON puro.")

    def _d(p, h="Tipo de dispositivo alvo."):
        p.add_argument("--device", "-d", choices=["DESKTOP", "MOBILE", "TABLET", "AGNOSTIC"], default=None, help=h)

    def _sid(p, h1="ID ou URL da sessão do Jules.", h2="ID ou URL da sessão (flag alternativa)."):
        p.add_argument("session_id", nargs="?", help=h1)
        p.add_argument("--session-id", "-s", dest="session_id_flag", help=h2)

    p = _c("setup", "Analisa e configura o projeto atual.", cmd_setup, ["init"])
    p.add_argument("--auto", action="store_true", help="Executa o setup de forma automática/não-interativa.")
    p.add_argument("--path", help="Diretório alvo específico para configurar (padrão: diretório atual).")
    p.add_argument("--force", action="store_true", help="Sobrescreve arquivos de template existentes.")
    p.add_argument("--dry-run", action="store_true", help="Simula a execução do setup sem escrever nada no disco.")
    p.add_argument("--prompt", "-p", action="store_true", help="Exibe o Prompt Mestre de Auto-Configuração para colar em IAs.")
    p = _c("prompt", "Exibe ou sintetiza com IA o Prompt de Desenvolvimento.", cmd_prompt)
    p.add_argument("--synthesize", "-s", help="Ideia informal a ser sintetizada em prompt estruturado com IA.")
    p.add_argument("--role", "-r", default="general", help="Especialidade para sintetização do prompt.")
    p = _c("check", "Valida chaves e configurações do projeto ativo.", cmd_check, ["status"])
    p.add_argument("--json", action="store_true", help="Exibe o diagnóstico em formato JSON estruturado.")
    p = _c("config", "Configura preferências de IA, quotas e autorizações do AMB_V2.", cmd_config, ["settings", "pref"])
    p.add_argument("--gemini-confirm", choices=["on", "off", "true", "false"], help="Ativa (on) ou desativa (off) a exigência de autorização manual a cada chamada ao Gemini.")
    p = _c("monitor", "Sentinela em tempo real (Jules) com suporte a auto-resposta Gemini.", cmd_monitor, ["watch", "sentinel"])
    p.add_argument("--interactive", "-i", action="store_true", help="Abre o menu interativo cognitivo (Advisor) para inspecionar e responder pendências.")
    p.add_argument("--auto-approve", "-y", action="store_true", help="Aprova e responde chats automaticamente via Gemini.")
    p.add_argument("--check-once", "-1", action="store_true", help="Executa apenas uma rodada de checagem e encerra.")
    p.add_argument("--interval", type=int, default=15, help="Intervalo de polling em segundos (padrão: 15s).")
    p = _c("advisor", "Menu cognitivo para tirar dúvidas pendentes do Jules com IA.", cmd_advisor, ["ask"])
    _sid(p, "ID ou URL da sessão do Jules (opcional).", "ID ou URL da sessão do Jules.")
    p.add_argument("--message", "-m", help="Mensagem direta manual a ser enviada ao chat.")
    p.add_argument("--auto-approve", "-y", action="store_true", help="Responde ou aprova automaticamente com IA sem confirmação.")
    _c("gui", "Abre o Assistente Gráfico Interativo (UI Wizard) para montagem de comandos e gestão de ambiente (.env).", cmd_gui, ["ui", "wizard"])
    p = _c("agent", "Executor de personas autônomas de manutenção.", cmd_agent, ["persona"])
    p.add_argument("--role", "-r", help="Nome da persona (ex: engineer, etc.).")
    p.add_argument("--all", "-a", action="store_true", help="Executa todas as personas em lote.")
    p.add_argument("--prompt", "-p", help="Caminho de um arquivo markdown (.md) com prompt estruturado.")
    p.add_argument("--task", "-t", help="Instruções ou escopo adicional.")
    p.add_argument("--list", "-l", action="store_true", help="Lista todas as personas disponíveis.")
    p.add_argument("--agy", "--local", action="store_true", default=False, help="Executa o agente localmente via agy CLI (por padrão despacha para o Google Jules na nuvem).")
    p.add_argument("--dispatch-jules", "-j", action="store_true", help="(Legado) Força o despacho para o Google Jules (comportamento padrão).")
    p.add_argument("--loop", "-c", "--continuous", action="store_true", help="Executa o ciclo contínuo e autônomo de personas.")
    p.add_argument("--max-cycles", type=int, help="Limite de ciclos no modo loop (se omitido, roda continuamente).")
    p.add_argument("--branch", "-b", help="Branch de início para o Jules (se omitido, auto-detecta a branch ativa do Git).")
    p.add_argument("--personas-dir", help="Pasta customizada de personas.")

    p = _c("jules", "Comandos de integração com o Google Jules.", cmd_jules)
    js = p.add_subparsers(dest="jules_cmd", help="Subcomandos do Jules")
    j = _sc(js, "status", "Diagnóstico de conectividade, credenciais e sessões ativas do Jules.", ["check"])
    j.add_argument("--repo", "-r", help="Filtra o diagnóstico por repositório específico.")
    _j(j)
    j = _sc(js, "sources", "Lista fontes e repositórios conectados à conta Google Jules.", ["source"])
    _j(j)
    j = _sc(js, "list", "Lista sessões recentes do repositório ou de toda a conta.")
    j.add_argument("--limit", "-n", type=int, default=10, help="Limite de sessões exibidas (padrão: 10).")
    j.add_argument("--all", "-a", action="store_true", help="Lista sessões de todos os repositórios (desativa filtro por repo atual).")
    j.add_argument("--repo", "-r", help="Filtra por repositório específico (ex: org/repo).")
    j.add_argument("--state", "-s", help="Filtra por estado (ex: AWAITING_USER_FEEDBACK, IN_PROGRESS, COMPLETED, FAILED).")
    _j(j)
    j = _sc(js, "get", "Exibe detalhes, PR ou faz streaming ao vivo da sessão.")
    _sid(j, "ID ou URL da sessão do Jules.")
    j.add_argument("--watch", "-w", action="store_true", help="Acompanha em tempo real as atividades e saídas da sessão.")
    _j(j)
    j = _sc(js, "create", "Cria uma nova sessão no Jules Cloud VM.")
    j.add_argument("--prompt", "-p", required=True, help="Prompt ou caminho de arquivo com instruções da tarefa.")
    j.add_argument("--title", "-t", help="Título descritivo da sessão.")
    j.add_argument("--branch", "-b", help="Branch base inicial no repositório (padrão: auto-detecta a branch ativa do Git).")
    j.add_argument("--source", help="Fonte conectada no Jules (padrão: auto-detecta sources/github/owner/repo).")
    _j(j)
    j = _sc(js, "reply", "Responde uma dúvida com IA (ou envia mensagem direta se --message).", ["advisor", "ask"])
    _sid(j, "ID ou URL da sessão do Jules (opcional).", "ID ou URL da sessão (opcional; se omitido, lista todas as sessões pendentes).")
    j.add_argument("--message", "-m", help="Mensagem direta manual a ser enviada ao chat.")
    j.add_argument("--auto-approve", "-y", action="store_true", help="Envia resposta gerada pelo Gemini sem pedir confirmação.")
    j.add_argument("--force", "-f", action="store_true", help="Força envio ignorando guardrail de mensagens consecutivas do usuário.")
    j = _sc(js, "approve", "Aprova o plano de execução de uma sessão.")
    _sid(j, "ID ou URL da sessão do Jules.")
    j.add_argument("--force", "-f", action="store_true", help="Força aprovação sem checar se o plano está em estado pendente.")
    _j(j)
    j = _sc(js, "merge", "Detecta o PR da sessão, aprova, faz merge no GitHub e valida localmente.")
    _sid(j, "ID ou URL da sessão do Jules para detectar o PR.", "ID da sessão para detectar o PR (flag alternativa).")
    j.add_argument("--auto-latest", "-a", action="store_true", help="Detecta automaticamente o PR aberto mais recente.")
    j.add_argument("--branch", "-b", default="main", help="Branch de destino local após merge (padrão: main).")
    j = _sc(js, "clean", "Audita e remove na nuvem sessões do Jules já integradas.", ["cleanup"])
    j.add_argument("--force", "-f", action="store_true", help="Remove sem pedir confirmação.")
    j.add_argument("--failed", action="store_true", help="Remove todas as sessões que estão em estado de falha (FAILED).")
    j.add_argument("--merged", action="store_true", help="Remove sessões cujos PRs já foram integrados ao Git.")
    j.add_argument("--id", help="Remove uma sessão específica por ID.")

    p = _c("stitch", "Comandos de integração com o Google Stitch SDK.", cmd_stitch)
    ss = p.add_subparsers(dest="stitch_cmd", help="Subcomandos do Stitch")
    s = _sc(ss, "list", "Lista todas as telas geradas no projeto Stitch.")
    s.add_argument("--project-id", help="ID do projeto Stitch (padrão: lê do .env).")
    _j(s)
    s = _sc(ss, "generate", "Gera uma nova tela via Stitch.")
    s.add_argument("--prompt", "-p", required=True, help="Descrição visual da tela.")
    s.add_argument("--title", "-t", help="Título da tela.")
    _d(s, "Tipo de dispositivo alvo (DESKTOP, MOBILE, TABLET, AGNOSTIC; padrão: lê do projeto ou .env).")
    s.add_argument("--output", "-o", help="Caminho do arquivo para salvar o HTML da tela.")
    _j(s)
    s = _sc(ss, "refine", "Refina uma tela existente no Stitch com novas instruções.")
    s.add_argument("--screen-id", "-s", required=True, help="ID da tela.")
    s.add_argument("--prompt", "-p", required=True, help="Instruções de edição e refinamento visual.")
    _d(s)
    s.add_argument("--output", "-o", help="Caminho do arquivo para salvar o novo HTML refinado.")
    _j(s)
    s = _sc(ss, "get", "Obtém o código HTML/CSS e assets de uma tela.")
    s.add_argument("--screen-id", "-s", required=True, help="ID da tela.")
    s.add_argument("--output", "-o", help="Caminho do arquivo para salvar o código HTML da tela.")
    _j(s)
    s = _sc(ss, "variants", "Gera variantes visuais exploratórias de uma tela.")
    s.add_argument("--screen-id", "-s", required=True, help="ID da tela base.")
    s.add_argument("--prompt", "-p", required=True, help="Instruções de variação.")
    s.add_argument("--count", "-c", type=int, default=3, help="Número de variantes (padrão: 3).")
    _d(s)
    _j(s)
    s = _sc(ss, "download", "Baixa todas as telas e assets do projeto Stitch para um diretório local.")
    s.add_argument("--output", "-o", default="./stitch_assets", help="Diretório local de destino dos assets baixados.")
    s.add_argument("--project-id", help="ID do projeto Stitch (padrão: lê do .env).")
    _j(s)
    s = _sc(ss, "project", "Consulta detalhes do projeto Stitch ativo.")
    s.add_argument("--project-id", help="ID do projeto Stitch (padrão: lê do .env).")
    _j(s)
    s = _sc(ss, "sync", "Sincroniza design tokens do design.md com o Design System do Stitch.")
    s.add_argument("--file", "-f", help="Caminho do arquivo design.md.")
    _j(s)
    s = _sc(ss, "call", "Invoca uma ferramenta arbitrária do Stitch SDK via JSON-RPC.")
    s.add_argument("tool", help="Nome da ferramenta (ex: get_screen, list_screens, download_assets).")
    s.add_argument("payload", nargs="?", default="{}", help="Payload JSON da ferramenta.")
    _j(s)

    p = _c("antigravity", "Comandos de inferência cognitiva e SDK Google Antigravity.", cmd_antigravity, ["agy"])
    ag = p.add_subparsers(dest="agy_cmd", help="Subcomandos do Antigravity")
    a = _sc(ag, "status", "Verifica status do runtime agy, chaves e regras ativas.", ["check"])
    a.add_argument("--json", action="store_true", help="Exibe o status em formato JSON estruturado.")
    a = _sc(ag, "prompt", "Sintetiza uma ideia informal em prompt executivo formal com IA.", ["synthesize", "synth"])
    a.add_argument("--idea", "-i", required=True, help="Ideia informal ou requisito a sintetizar.")
    a.add_argument("--role", "-r", default="general", help="Especialidade ou papel da persona (padrão: general).")
    a.add_argument("--output", "-o", help="Caminho do arquivo para salvar o prompt sintetizado.")
    a = _sc(ag, "validate", "Audita conformidade arquitetural de um arquivo contra as regras do repositório.", ["audit", "lint"])
    a.add_argument("file", help="Caminho do arquivo a ser auditado.")
    a.add_argument("--json", action="store_true", help="Exibe o relatório em JSON estruturado.")
    a = _sc(ag, "rules", "Lista e inspeciona as regras arquiteturais descobertas no projeto.")
    a.add_argument("--json", action="store_true", help="Exibe a lista de regras em JSON.")
    a.add_argument("--content", "-c", action="store_true", help="Exibe o conteúdo integral consolidado das regras.")
    a = _sc(ag, "run", "Executa inferência direta com prompt arbitrário via modelo cognitivo.", ["eval"])
    a.add_argument("prompt", help="Prompt para inferência cognitiva.")
    a.add_argument("--system", "-s", help="Instrução de sistema opcional.")
    a.add_argument("--model", "-m", help="Modelo específico do Gemini (ex: gemini-3.8-flash).")
    a.add_argument("--temperature", "-t", type=float, default=0.2, help="Temperatura de amostragem (padrão: 0.2).")
    a.add_argument("--output", "-o", help="Salva a saída em arquivo.")

    p = _c("validate", "Audita um arquivo contra as regras arquiteturais do repositório.", cmd_validate, ["lint", "audit"])
    p.add_argument("file", help="Caminho do arquivo de código a ser auditado.")

    p = _c("pipeline", "Roda o orquestrador Design-to-Deploy (Stitch -> Jules -> GitHub) com prompts separados para Design e Engenharia.", cmd_pipeline, ["run", "deploy"])
    p.add_argument("--stitch-prompt", "-s", help="Caminho do arquivo markdown contendo a especificação visual para o Stitch.")
    p.add_argument("--jules-prompt", "-j", help="Caminho do arquivo markdown contendo as instruções técnicas para o Jules.")
    p.add_argument("--prompt-file", "-f", help="Arquivo único unificado (.md) com divisões claras entre [STITCH_DESIGN] e [JULES_DEV].")
    p.add_argument("--resume-session", "-r", help="ID da sessão Jules para retomar o monitoramento sem criar nova.")
    p.add_argument("--skip-stitch", action="store_true", help="Pula a geração de UI no Stitch, indo direto ao Jules.")
    p.add_argument("--no-qa", action="store_true", help="Desabilita o teste QA local automático no final.")
    p.add_argument("--auto-approve", "-y", action="store_true", help="Aprova planos no Jules automaticamente.")
    p.add_argument("--repo", help="Repositório GitHub no formato 'dono/repo' (padrão: auto-detectado via git).")
    _d(p, "Tipo de dispositivo para geração do Stitch.")
    p.add_argument("--edit-screen-id", help="Refina uma tela existente no Stitch em vez de criar uma nova.")
    p.add_argument("--screen-id", help="Utiliza uma tela já existente no Stitch como ponto de partida (não recria).")
    p.add_argument("--sync-ds", action="store_true", help="Sincroniza os design tokens locais antes de gerar a tela.")
    p.add_argument("--branch", "-b", help="Branch alvo para PR e checkout (default: detecta a atual).")

    p = _c("schema", "Inspeciona tabelas e colunas de schemas do banco de dados (Read-Only).", cmd_schema, ["db"])
    p.add_argument("target", nargs="?", default=None, help="Nome da tabela ou módulo a filtrar (ex: kanban, agenda, projects).")

    p = _c("context", "Gera o roteiro de leitura de arquivos por camadas para a IA.", cmd_context, ["ctx", "ai-context"])
    p.add_argument("module", nargs="?", default="agenda", help="Nome do módulo ou pasta para rastrear (ex: agenda, kanban, projects).")
    p.add_argument("--json", action="store_true", help="Retorna o resultado em JSON estruturado.")

    p = _c("git", "Comandos de controle de versão e ciclo de vida de Pull Requests via Git & GitHub CLI.", cmd_git)
    gs = p.add_subparsers(dest="git_cmd", help="Subcomandos do Git")
    g = _sc(gs, "status", "Exibe status detalhado do repositório Git, branches, upstream e GitHub CLI.")
    g.add_argument("--json", action="store_true", help="Exibe o status em formato JSON estruturado.")
    g = _sc(gs, "sync", "Sincroniza a branch ativa com o repositório remoto (fetch + pull com auto-stash).")
    g.add_argument("--remote", "-r", default="origin", help="Nome do remote (padrão: origin).")
    g.add_argument("--branch", "-b", help="Nome da branch (padrão: branch ativa).")
    g.add_argument("--no-stash", action="store_false", dest="auto_stash", help="Desabilita stash automático se a working tree estiver modificada.")
    g = _sc(gs, "diff", "Exibe o diff unificado de arquivos alterados ou contra a branch base.")
    g.add_argument("file", nargs="?", default=None, help="Caminho do arquivo específico (opcional).")
    g.add_argument("--base", "-b", help="Branch base para comparação.")
    g.add_argument("--cached", action="store_true", help="Exibe diff das alterações preparadas (staged).")

    prs = _sc(gs, "pr", "Gerenciador de Pull Requests no GitHub via GitHub CLI.").add_subparsers(dest="pr_cmd", help="Ações de Pull Request")
    pr = _sc(prs, "list", "Lista Pull Requests abertos no repositório.")
    pr.add_argument("--repo", help="Repositório alvo (dono/repo).")
    pr.add_argument("--no-drafts", action="store_true", help="Oculta PRs em modo draft.")
    _j(pr)
    pr = _sc(prs, "get", "Exibe detalhes completos de um Pull Request.")
    pr.add_argument("number", type=int, help="Número do Pull Request.")
    pr.add_argument("--repo", help="Repositório alvo (dono/repo).")
    _j(pr)
    pr = _sc(prs, "create", "Cria um novo Pull Request no GitHub.")
    pr.add_argument("--title", "-t", required=True, help="Título do PR.")
    pr.add_argument("--body", "-b", default="", help="Descrição detalhada do PR.")
    pr.add_argument("--base", help="Branch base de destino.")
    pr.add_argument("--head", help="Branch de origem das alterações.")
    pr.add_argument("--draft", action="store_true", help="Cria o PR como rascunho (Draft).")
    pr.add_argument("--repo", help="Repositório alvo.")
    _j(pr)
    pr = _sc(prs, "ready", "Marca um PR em draft como pronto para revisão.")
    pr.add_argument("number", type=int, help="Número do Pull Request.")
    pr.add_argument("--repo", help="Repositório alvo.")
    pr = _sc(prs, "approve", "Aprova formalmente o Pull Request.")
    pr.add_argument("number", type=int, help="Número do Pull Request.")
    pr.add_argument("--body", default="✅ Aprovado pelo AMB_V2.", help="Comentário de aprovação.")
    pr.add_argument("--repo", help="Repositório alvo.")
    pr = _sc(prs, "merge", "Realiza o merge do Pull Request.")
    pr.add_argument("number", type=int, help="Número do Pull Request.")
    pr.add_argument("--no-squash", action="store_false", dest="squash", help="Não realizar squash merge.")
    pr.add_argument("--keep-branch", action="store_false", dest="delete_branch", help="Não deletar a branch remota após merge.")
    pr.add_argument("--repo", help="Repositório alvo.")
    pr = _sc(prs, "close", "Fecha um Pull Request no GitHub.")
    pr.add_argument("number", type=int, help="Número do Pull Request.")
    pr.add_argument("--comment", help="Comentário opcional ao fechar.")
    pr.add_argument("--delete-branch", action="store_true", help="Deletar a branch associada.")
    pr.add_argument("--repo", help="Repositório alvo.")

    return parser
